### ISSUE TITLE
build ，No binaries are generated

### ISSUE THREAD

**Issue by steamsv** [sfackler/rust-socks#20]
No binaries are generated
<img width="465" alt="image" src="https://user-images.githubusercontent.com/49923565/182197221-45c52421-696a-46b5-b432-dd1b26a9d967.png">

**Comment by sfackler** [comment]
What binary would you expect to exist?

**Comment by steamsv** [comment]
linux x86_64

**Comment by sfackler** [comment]
What would that binary do?

**Comment by steamsv** [comment]
Start a socks5 server

**Comment by sfackler** [comment]
This repository does not implement a socks5 server.
