### ISSUE TITLE
Figure out how to use heap allocations more sparingly.

### ISSUE THREAD

**Issue by ghost** [sfackler/rust-socks#3]
It might be possible to re-use a single heap allocated buffer and store it in the `struct`.

Also it might be possible to use `ArrayVec`s in some cases.

**Comment by sfackler** [comment]
This is referring to `Socks5Datagram` I'm guessing?

**Comment by ghost** [comment]
I did not read the source very closely, I'm just concerned with the amount of heap allocations.

**Comment by sfackler** [comment]
Are you running into specific performance problems? Other than `Socks5Datagram`, there should only be heap allocations during the initial handshake.

**Comment by ghost** [comment]
Okay, but I think https://github.com/sfackler/rust-socks/blob/master/src/v5.rs#L116 could be a ArrayVec, correct me if i'm wrong.

Edit: I'm sure there are other places it would work as well.

**Comment by sfackler** [comment]
Sure, there are all kinds of data structures that *could* be used there. The question is if it actually matters at all in practice.
