### ISSUE TITLE
why no executable file generated in 'release' dir?

### ISSUE THREAD

**Issue by luckypoem** [sfackler/rust-socks#9]
hi.

root@ar:~/rust-socks# cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Fetch [============================================>          ]  82.91%
       Fetch [===================================================>   ]  96.35%
 Downloading libc v0.2.43                                                       
 Downloading byteorder v1.2.6                                                   
   Compiling byteorder v1.2.6                                                   
   Compiling libc v0.2.43
   Compiling socks v0.3.1 (file:///root/rust-socks)
    Finished release [optimized] target(s) in 25.65 secs
root@ar:~/rust-socks# 
root@ar:~/rust-socks# 
root@ar:~/rust-socks# ls
Cargo.lock  Cargo.toml	LICENSE-APACHE	LICENSE-MIT  README.md	src  target
root@ar:~/rust-socks# cd target/release
root@ar:~/rust-socks/target/release# ls
build  deps  examples  incremental  libsocks.d	libsocks.rlib  native
root@ar:~/rust-socks/target/release# ls build
root@ar:~/rust-socks/target/release# ls deps
byteorder-29b1e6c8adac7ade.d	    liblibc-ddc047373b8df290.rlib
libbyteorder-29b1e6c8adac7ade.rlib  libsocks-42e117dbf84ea3d6.rlib
libc-ddc047373b8df290.d		    socks-42e117dbf84ea3d6.d
root@ar:~/rust-socks/target/release# ls examples
root@ar:~/rust-socks/target/release# ls  native
root@ar:~/rust-socks/target/release#

tks

**Comment by sfackler** [comment]
This crate is a library, not an executable. The `libsocks-42e117dbf84ea3d6.rlib` is what the crate produces.
